Update loki config to support azure blob as an option

diff --git a/docker-swarm-templates/docker-compose.grafana-stack.yml b/docker-swarm-templates/docker-compose.grafana-stack.yml
--- a/docker-swarm-templates/docker-compose.grafana-stack.yml
+++ b/docker-swarm-templates/docker-compose.grafana-stack.yml
@@ -83,9 +83,12 @@
 #   #-      >   && echo "'${password}'" \
 #   #-      >   && sudo docker run --rm httpd htpasswd -nb ${LOKI_USERNAME:?} ${password}
 #   LOKI_PASSWORD_HASH='$apr1$wcCsl.As$SAbn61uxmjxbeyRs29eZk0'
+#   #-  - LOKI_OBJECT_STORE -
+#   #-    Object storage backend for Loki. Supported values: s3, azure.
+#   LOKI_OBJECT_STORE=s3
 #   #-  - LOKI_S3_USE_MINIO -
 #   #-    The endpoint for the S3 bucket compatible storage.
-#   LOKI_S3_USE_MINIO=true
+#   LOKI_S3_USE_MINIO=false
 #   #-  - LOKI_S3_ENDPOINT -
 #   #-    The endpoint for the S3 bucket compatible storage.
 #   LOKI_S3_ENDPOINT=<HOST_IP>:9000
@@ -101,6 +104,15 @@
 #   #-  - SECRET_ACCESS_KEY -
 #   #-    The password for S3 bucket
 #   SECRET_ACCESS_KEY=supersecret
+#   #-  - LOKI_AZURE_STORAGE_ACCOUNT_NAME -
+#   #-    Azure Storage account name used when LOKI_OBJECT_STORE=azure.
+#   LOKI_AZURE_STORAGE_ACCOUNT_NAME=
+#   #-  - LOKI_AZURE_STORAGE_ACCOUNT_KEY -
+#   #-    Azure Storage account key used when LOKI_OBJECT_STORE=azure.
+#   LOKI_AZURE_STORAGE_ACCOUNT_KEY=
+#   #-  - LOKI_AZURE_STORAGE_CONTAINER_NAME -
+#   #-    Azure Blob container used when LOKI_OBJECT_STORE=azure.
+#   LOKI_AZURE_STORAGE_CONTAINER_NAME=loki
 #   #-  - LOKI_GRPC_SERVER_MAX_RECV_MSG_SIZE -
 #   #-    Limit on the size of a gRPC message this server can receive (bytes).
 #   LOKI_GRPC_SERVER_MAX_RECV_MSG_SIZE=
@@ -179,27 +191,54 @@ x-service-defaults:
 
         echo "### Writing custom local-config.yaml ###"
 
-        echo "  - Create custom S3 connection config"
-        s3_storage_url_credentials="$${ACCESS_KEY_ID:-}:$${SECRET_ACCESS_KEY:-}"
-        if [ "$${LOKI_S3_USE_MINIO:-}" = "true" ]; then
-          # MinIO reqires that we use s3forcepathstyle
-          s3_force_path_style="true"
-          if [ "$${s3_storage_url_credentials:-}" != ":" ]; then
-            # http<s>://<username>:<secret>@<fqdn>:<port>
-            s3_storage_url="http://$${s3_storage_url_credentials:?}@$${LOKI_S3_ENDPOINT:?}"
+        loki_object_store="$${LOKI_OBJECT_STORE:-s3}"
+
+        if [ "$${loki_object_store}" = "azure" ]; then
+          echo "  - Create custom Azure Blob connection config"
+          : "$${LOKI_AZURE_STORAGE_ACCOUNT_NAME:?}"
+          : "$${LOKI_AZURE_STORAGE_ACCOUNT_KEY:?}"
+          : "$${LOKI_AZURE_STORAGE_CONTAINER_NAME:?}"
+          loki_storage_backend_config="$$(cat << AZURE_CONFIG
+          azure:
+            account_name: $${LOKI_AZURE_STORAGE_ACCOUNT_NAME:?}
+            account_key: $${LOKI_AZURE_STORAGE_ACCOUNT_KEY:?}
+            container_name: $${LOKI_AZURE_STORAGE_CONTAINER_NAME:?}
+        AZURE_CONFIG
+        )"
+        elif [ "$${loki_object_store}" = "s3" ]; then
+          echo "  - Create custom S3 connection config"
+          s3_storage_url_credentials="$${ACCESS_KEY_ID:-}:$${SECRET_ACCESS_KEY:-}"
+          if [ "$${LOKI_S3_USE_MINIO:-}" = "true" ]; then
+            # MinIO reqires that we use s3forcepathstyle
+            s3_force_path_style="true"
+            if [ "$${s3_storage_url_credentials:-}" != ":" ]; then
+              # http<s>://<username>:<secret>@<fqdn>:<port>
+              s3_storage_url="http://$${s3_storage_url_credentials:?}@$${LOKI_S3_ENDPOINT:?}"
+            else
+              echo "ERROR! No ACCESS_KEY_ID and/or SECRET_ACCESS_KEY set. Exit!"
+              exit 1
+            fi
           else
-            echo "ERROR! No ACCESS_KEY_ID and/or SECRET_ACCESS_KEY set. Exit!"
-            exit 1
+            # AWS recommends that we don't use s3forcepathstyle
+            s3_force_path_style="false"
+            # s3://<region>
+            s3_storage_url="s3://$${AWS_REGION:?}"
+            if [ "$${s3_storage_url_credentials:-}" != ":" ]; then
+              # s3://<access_key>:<uri-encoded-secret-access-key>@<region>
+              s3_storage_url="s3://$${s3_storage_url_credentials:?}@$${AWS_REGION:?}"
+            fi
           fi
+
+          loki_storage_backend_config="$$(cat << S3_CONFIG
+          aws:
+            s3forcepathstyle: $${s3_force_path_style:?}
+            s3: $${s3_storage_url:?}
+            bucketnames: $${LOKI_S3_BUCKET_NAME:?}
+        S3_CONFIG
+          )"
         else
-          # AWS recommends that we don't use s3forcepathstyle
-          s3_force_path_style="false"
-          # s3://<region>
-          s3_storage_url="s3://$${AWS_REGION:?}"
-          if [ "$${s3_storage_url_credentials:-}" != ":" ]; then
-            # s3://<access_key>:<uri-encoded-secret-access-key>@<region>
-            s3_storage_url="s3://$${s3_storage_url_credentials:?}@$${AWS_REGION:?}"
-          fi
+          echo "ERROR! Unsupported LOKI_OBJECT_STORE '$${loki_object_store}'. Supported values: s3, azure." >&2
+          exit 1
         fi
 
         echo "  - Write out config to /etc/loki/local-config.yaml"
@@ -222,7 +261,7 @@ x-service-defaults:
           configs:
             - from: 2024-03-29
               store: tsdb
-              object_store: s3
+              object_store: $${loki_object_store:?}
               schema: v13
               index:
                 prefix: index_
@@ -241,10 +280,7 @@ x-service-defaults:
             active_index_directory: /loki/tsdb/index
             cache_location: /loki/tsdb/index_cache
             cache_ttl: 24h
-          aws:
-            s3forcepathstyle: $${s3_force_path_style:?}
-            s3: $${s3_storage_url:?}
-            bucketnames: $${LOKI_S3_BUCKET_NAME:?}
+        $${loki_storage_backend_config}
 
 
         ingester_rf1:
@@ -291,7 +327,7 @@ x-service-defaults:
         compactor:
           working_directory: /tmp/compactor
           retention_enabled: true 
-          delete_request_store: s3
+          delete_request_store: $${loki_object_store:?}
 
         # Create a read cache of queries
         query_range:
@@ -331,12 +367,16 @@ x-service-defaults:
     environment:
       <<: *environment_defaults
       TRAEFIK_PATH_PREFIX_LOKI: ${TRAEFIK_PATH_PREFIX_LOKI:-}
+      LOKI_OBJECT_STORE: ${LOKI_OBJECT_STORE:-s3}
       LOKI_S3_USE_MINIO: ${LOKI_S3_USE_MINIO:-false}
       LOKI_S3_ENDPOINT: ${LOKI_S3_ENDPOINT:-s3.amazonaws.com}
-      LOKI_S3_BUCKET_NAME: ${LOKI_S3_BUCKET_NAME:?}
+      LOKI_S3_BUCKET_NAME: ${LOKI_S3_BUCKET_NAME:-}
       AWS_REGION: ${AWS_REGION:-}
       ACCESS_KEY_ID: ${ACCESS_KEY_ID:-}
       SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY:-}
+      LOKI_AZURE_STORAGE_ACCOUNT_NAME: ${LOKI_AZURE_STORAGE_ACCOUNT_NAME:-}
+      LOKI_AZURE_STORAGE_ACCOUNT_KEY: ${LOKI_AZURE_STORAGE_ACCOUNT_KEY:-}
+      LOKI_AZURE_STORAGE_CONTAINER_NAME: ${LOKI_AZURE_STORAGE_CONTAINER_NAME:-loki}
       GRPC_SERVER_MAX_RECV_MSG_SIZE: ${LOKI_GRPC_SERVER_MAX_RECV_MSG_SIZE:-20971520}
       GRPC_SERVER_MAX_SEND_MSG_SIZE: ${LOKI_GRPC_SERVER_MAX_SEND_MSG_SIZE:-20971520}
       REJECT_OLD_SAMPLES_MAX_AGE: ${LOKI_REJECT_OLD_SAMPLES_MAX_AGE:-24h}
@@ -977,10 +1017,6 @@ services:
             location = /ping {
               return 200 'OK';
               auth_basic off;
-            }
-
-            location /.well-known/acme-challenge/ {
-                root /var/www/certbot;
             }
 
             location = $${TRAEFIK_PATH_PREFIX_LOKI:-}/ring {
